# Generated by Django 5.2.1 on 2025-06-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField()),
                ('aadhar_card_number', models.CharField(max_length=12, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('driving_license', models.CharField(max_length=20, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='agent_profiles/')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
