# Generated by Django 5.1.1 on 2025-06-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAgent',
        ),
    ]
