# Generated by Django 5.2.1 on 2025-07-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
