# Generated by Django 5.2.1 on 2025-07-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_deliveryagent_is_active_deliveryagent_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='is_staff',
        ),
    ]
