# Generated by Django 5.1.1 on 2025-06-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='agent/id_photos/'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='agent/profile_pictures/'),
        ),
    ]
