# Generated by Django 5.1.1 on 2025-06-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_deliveryagent_id_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAgent',
        ),
    ]
