# Generated by Django 5.1.1 on 2025-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0005_delete_deliveryagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('agent_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('aadhar_card_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('driving_license', models.CharField(max_length=30)),
                ('id_photo', models.ImageField(upload_to='agent/id_photos/')),
                ('profile_picture', models.ImageField(upload_to='agent/profile_pictures/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
