# Generated by Django 5.2.1 on 2025-06-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='email_id',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
