# Generated by Django 5.2.1 on 2025-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
