# Generated by Django 5.2.1 on 2025-06-25 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_alter_deliveryagent_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='agent',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='agent.deliveryagent'),
        ),
    ]
