# Generated by Django 5.2.1 on 2025-06-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_passwordresetotp_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_verified',
        ),
    ]
