# Generated by Django 5.2.1 on 2025-06-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_remove_passwordresetotp_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryagent',
            old_name='email_id',
            new_name='email',
        ),
    ]
