# Generated by Django 5.2.1 on 2025-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_rename_email_id_deliveryagent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
