# Generated by Django 5.2.1 on 2025-06-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_passwordresetotp_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='agent',
        ),
    ]
