# Generated by Django 5.2.1 on 2025-06-26 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_remove_passwordresetotp_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='agent',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='agent.deliveryagent'),
        ),
    ]
