# Generated by Django 5.1.1 on 2025-06-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
