# Generated by Django 5.1.1 on 2025-06-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profilees_delete_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilees',
        ),
    ]
