# Generated by Django 5.1.1 on 2025-06-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
