# Generated by Django 5.1.1 on 2025-06-07 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cartitem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity_type',
            field=models.CharField(choices=[('250g', '250 grams'), ('500g', '500 grams'), ('1kg', '1 Kilogram'), ('2kg', '2 Kilograms')], default=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product')},
        ),
    ]
