# Generated by Django 5.1.1 on 2025-06-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity_type',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('250g', '250 grams'), ('500g', '500 grams'), ('1kg', '1 Kilogram'), ('2kg', '2 Kilograms')], default=True, max_length=10),
        ),
    ]
