# Generated by Django 5.2.1 on 2025-07-07 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_deliveryagent_is_active_and_more'),
        ('app', '0025_remove_orderaddressmapping_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddressmapping',
            name='assigned_at',
        ),
        migrations.AddField(
            model_name='orderaddressmapping',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.deliveryagent'),
        ),
    ]
