# Generated by Django 5.2.1 on 2025-07-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_orderaddressmapping_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='street',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
