# Generated by Django 5.2.1 on 2025-07-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_useraddress_city_useraddress_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='flat_no',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
